DATA SEGMENT
	SAVE DB 3 DUP(?)
	NUM DW 200 DUP(?) 
DATA ENDS  
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA 
START:	MOV AX,DATA
	MOV DS,AX       
	MOV CX,200       
	XOR BX,BX       
	XOR DX,DX       
	LEA SI,NUM       
	SUB SI,2
NEXT1:	ADD SI,2
	CMP word ptr [SI],0
	JNZ NZ
	INC BL
	JMP OK
NZ:   	TEST [SI],8000H
	JNZ N
        INC DH 
JMP 	OK  
N:    	INC DL 
OK:   	LOOP NEXT1
	MOV SAVE,DH 
	MOV SAVE+1,DL
       	MOV SAVE+2,BL
       	MOV AH,4CH
       	INT 21H
CODE ENDS
END START 